# Railway configuration for the Whoblockwho bot
version: 2

services:
  app:
    # Build configuration
    build:
      dockerfile: Dockerfile
    
    # Environment settings
    variables:
      NODE_ENV: production
      PORT: 3000
    
    # Resource limits (adjust as needed)
    resources:
      memory: 512
      cpu: 500
    
    # Health check configuration
    healthcheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3
    
    # Restart policy
    restart: always
